#page title
page_title: 'Chipp Studio | Indie Development'

# App Info
# ios_app_id: 6453882470
# ios_app_country: us

# presskit_download_link: https://headroompublic.ams3.digitaloceanspaces.com/Headroom_PressKit.zip

app_icon: images/chipp_studio_icon.png
app_name: 'Chipp Studio'
app_price: Free

# Meta tags optimisation
description: 'Chipp Studio is a boutique indie development studio specializing in crafting high-quality Mac and iOS applications. With a focus on user experience, performance, and elegant design, Chipp Studio develops custom solutions for both professionals and creative users.'
cover: images/meta_cover.png
keywords: Chipp Studio, indie development studio, Mac apps, iOS apps, Apple ecosystem, app development, custom app solutions, user experience, app design, professional tools, creative tools, indie apps, iOS development, macOS development, app performance, app innovation, software for professionals, app portfolio

enable_smart_app_banner: false

# Information About Yourself
your_name: Konstantin Tšistjakov                               
your_link: https://chippstudio.ee                  
your_city: Tallinn                                
email_address: info@chippstudio.ee
# facebook_username: 61563619501214
# instagram_username: headroom.podcastapp
# twitter_username: useheadroomapp
# linkedin_username: 102554801
# mastodon_link: mastodon.social/@headroom
# github_username: 
# youtube_username:

socials:
  - social:
    title: LinkedIn
    url: https://www.linkedin.com/in/konstantints/
  - social:
    title: X (Twitter)
    url: https://x.com/ktsistjakov

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor/

include:
 - .well-known

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
