#page title
page_title                                : Chipp Studio | Indie development studio                                         

# General  Info

contact_email                             : info@chipptudio.ee                     
site_icon                                 : assets/chipplogo.png
studio_name                               : Chipp Studio
studio_description                        : Small indie development company <br> We develop apps which make life easier

# Apps
wordsstack_icon                           : assets/wordsstack.png
wordsstack_site                           : https://wordsstack.chippstudio.ee
wordsstack_appstore                       : https://apps.apple.com/us/app/words-stack/id1635180628
wordsstack_title                          : Words Stack
wordsstack_description                    : Build your own vocabulary on foreign language

# Information About Yourself
your_name                                 : Konstantin Tšistjakov                                
your_link                                 : https://emilbaehr.com                     
your_city                                 : Tallinn                                
email_address                             : konstantin@chippstudio.ee
facebook_username                         :                                           
instagram_username                        : chippstudio
twitter_username                          : ChippStudio
github_username                           : ChippStudio
youtube_username                          :



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1.0
topbar_title_color                        : "#70A2FA"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

body_background_color                     : "#ffffff"

link_color                                : "#70A2FA"

studio_title_color                        : "#22223B"
studio_description_color                  : "#22223B"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
