#page title
page_title: 'Chipp Studio | Indie Development'

# App Info
# ios_app_id: 6453882470
# ios_app_country: us

# presskit_download_link: https://headroompublic.ams3.digitaloceanspaces.com/Headroom_PressKit.zip

app_icon: images/chipp_studio_icon.png
app_name: 'Chipp Studio'
app_price: Free

# Meta tags optimisation
description: ''
cover: images/meta_cover.png
keywords: 

enable_smart_app_banner: false

# Header
header_title: Podcasting in the most efficient way
header_subtitle: Headroom is one solution for podcast production, providing all that you need to record, edit, prepare, and deliver an episode.

# Information About Yourself
your_name: Konstantin Tšistjakov                               
your_link: https://chippstudio.ee                  
your_city: Tallinn                                
email_address: info@chippstudio.ee
# facebook_username: 61563619501214
# instagram_username: headroom.podcastapp
# twitter_username: useheadroomapp
# linkedin_username: 102554801
# mastodon_link: mastodon.social/@headroom
# github_username: 
# youtube_username:

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor/

include:
 - .well-known

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
